export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const USER_SUCCESS = 'USER_SUCCESS';
export const AUTH_REGISTER_LOADING = ' AUTH_REGISTER_LOADING';
