export const FIELD_SUCCESS = 'FIELD_SUCCESS';
export const FIELD_ERROR = 'FIELD_ERROR';
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS';
export const FILTER_FIELD_SUCCESS = 'FILTER_FIELD_SUCCESS';
export const FILTER_FIELD_ERROR = 'FILTER_FIELD_ERROR';
