export const FIELD_SUCCESS = 'FIELD_SUCCESS';
export const FIELD_ERROR = 'FIELD_ERROR';
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS';
export const FILTER_FIELD_SUCCESS = 'FILTER_FIELD_SUCCESS';
export const FILTER_FIELD_ERROR = 'FILTER_FIELD_ERROR';
export const CREATE_FIELD_LOADING = 'CREATE_FIELD_';

export const FIELD_BYUSER_SUCCESS = 'FIELD_BYUSER_SUCCESS';
export const FIELD_BYUSER_ERROR = 'FIELD_BYUSER_ERROR';
export const FIELD_BYUSER_LOADING = 'FIELD_BYUSER_LOADING';
export const CLEAR_FIELDS_FILTER = 'CLEAR_FIELDS_FILTER';
