export const SHOW_CREATE_FIELD = 'SHOW_CREATE_FIELD';
export const HIDE_CREATE_FIELD = 'HIDE_CREATE_FIELD';
export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';
export const HIDE_LOGIN_FORM = 'HIDE_LOGIN_FORM';
export const SHOW_REGISTER_FORM = 'SHOW_REGISTER_FORM';
export const HIDE_REGISTER_FORM = 'HIDE_REGISTER_FORM';
